# Read JSON generated by check_cailbrations.py
# Visualize data

import json
import os

root = r"C:\Local\siivonek\Data\eye_tracking_data\own_test_data\eyetrack_results"
datafile = os.path.join(root, "data.json")

with open(datafile) as file:
    stuff = json.load(file)
    for subject in stuff:
        print(subject[0])
        for calib in subject[1]:
            print(calib[0])
            if not calib[1] == None:
                for interval in calib[1]:
                    print(interval)
            else:
                print(None)